# Generated by Django 6.0 on 2026-03-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_audit_fixes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteproduct',
            options={'verbose_name': 'Избранный продукт', 'verbose_name_plural': 'Избранные продукты'},
        ),
    ]
