# Generated by Django 6.0 on 2026-03-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_photo_uploaded_by_product_index'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productmodel',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='productmodel_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productmodel',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='productmodel_price_non_negative'),
        ),
    ]
