# Generated by Django 6.0 on 2026-03-13 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('phone_number', models.CharField(max_length=128, verbose_name='Номер телефона')),
                ('first_name', models.CharField(max_length=250, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Фамилия пользователя')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес доставки')),
                ('payment_type', models.CharField(choices=[('MBANK', 'MBank'), ('ONLINE_PAY', 'Онлайн оплата'), ('IN_CASH', 'Наличные')], default='IN_CASH', max_length=20, verbose_name='Тип оплаты')),
                ('delivery_type', models.CharField(choices=[('SELF_PICKUP', 'Самовывоз'), ('DELIVERY', 'Доставка')], default='SELF_PICKUP', max_length=20, verbose_name='Тип доставки')),
                ('order_status', models.CharField(choices=[('IN_PROCESSING', 'В обработке'), ('ACCEPTED', 'Принят'), ('CANCELED', 'Отменён'), ('REJECTED', 'Отклонён')], default='IN_PROCESSING', max_length=20, verbose_name='Статус заказа')),
                ('delivery_status', models.CharField(choices=[('IN_PROCESSING', 'В обработке'), ('IN_PROGRESS', 'В пути'), ('DELIVERED', 'Доставлен'), ('CANCELED', 'Отменён'), ('RETURNED', 'Возврат'), ('REJECTED', 'Отклонён')], default='IN_PROCESSING', max_length=20, verbose_name='Статус доставки')),
                ('payment_status', models.CharField(choices=[('WAITING_FOR_PAY', 'Ожидает оплаты'), ('PAID', 'Оплачен'), ('REFUNDED', 'Возврат')], default='WAITING_FOR_PAY', max_length=20, verbose_name='Статус оплаты')),
                ('check_photo', models.ImageField(blank=True, null=True, upload_to='orders/checks/', verbose_name='Фото чека')),
                ('sended_notifications', models.BooleanField(default=False, verbose_name='Отправлено уведомления')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('quantity', models.PositiveBigIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.productmodel', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
    ]
