# Generated by Django 6.0 on 2026-03-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_register_cleanup_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Ключ идемпотентности'),
        ),
    ]
