# Generated by Django 6.0 on 2026-03-13 13:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countryapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название банка')),
            ],
            options={
                'verbose_name': 'Тип банка',
                'verbose_name_plural': 'Типы банков',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг Магазина')),
                ('name', models.CharField(max_length=255, verbose_name='Название магазина')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес магазина')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/', verbose_name='Логотип')),
                ('phone_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Номер телефона')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание магазина')),
                ('theme', models.CharField(blank=True, choices=[('1', 'Тема 1'), ('2', 'Тема 2'), ('3', 'Тема 3'), ('4', 'Тема 4'), ('5', 'Тема 5'), ('6', 'Тема 6'), ('7', 'Тема 7'), ('8', 'Тема 8'), ('9', 'Тема 9'), ('10', 'Тема 10'), ('11', 'Тема 11'), ('12', 'Тема 12')], max_length=2, null=True, verbose_name='Тема магазина')),
                ('url_2gis', models.URLField(blank=True, null=True, verbose_name='URL на 2GIS')),
                ('url_goog_map', models.URLField(blank=True, null=True, verbose_name='URL на Google Maps')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='URL на Instagram')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='URL на Facebook')),
                ('telegram_url', models.URLField(blank=True, null=True, verbose_name='URL на Telegram')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='URL на YouTube')),
                ('whatsapp_url', models.URLField(blank=True, null=True, verbose_name='URL на WhatsApp')),
                ('tiktok_url', models.URLField(blank=True, null=True, verbose_name='URL на TikTok')),
                ('cashback_percent', models.PositiveSmallIntegerField(choices=[(1, '1%'), (2, '2%'), (3, '3%'), (4, '4%'), (5, '5%'), (6, '6%'), (7, '7%'), (8, '8%'), (9, '9%'), (10, '10%')], default=1, verbose_name='Cashback percent')),
                ('tariff_plan', models.CharField(choices=[('0', 'Бесплатный'), ('1', 'Базовый'), ('2', 'Стандарт'), ('3', 'Премиум')], default='0', max_length=1, verbose_name='Тарифный план')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Баланс магазина на текущий момент', max_digits=14, verbose_name='Баланс')),
                ('type_of_bonus_system', models.CharField(choices=[('1', 'Кэшбэк'), ('2', 'Баллы')], default='1', max_length=1, verbose_name='Тип системы начисления бонусов')),
                ('google_token', models.CharField(blank=True, max_length=20, null=True, verbose_name='Токен Google Аналитик')),
                ('latitude', models.CharField(blank=True, max_length=20, null=True, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, max_length=20, null=True, verbose_name='Долгота')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_stores', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='countryapi.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('button_text', models.CharField(max_length=100, verbose_name='Текст кнопки')),
                ('button_web_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL для веб-кнопки')),
                ('button_mob_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL для мобильной версии')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores/slides/', verbose_name='Изображение')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['ordering', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма пополнения')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда использован')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreBalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Введите сумму', max_digits=14, verbose_name='Сумма транзакции')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Пополнение'), ('OUTCOME', 'Списание')], max_length=10, verbose_name='Тип транзакции')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание транзакции')),
                ('balance_before', models.DecimalField(blank=True, decimal_places=2, help_text='Баланс магазина до транзакции', max_digits=14, null=True, verbose_name='Баланс до транзакции')),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, help_text='Баланс магазина после транзакции', max_digits=14, null=True, verbose_name='Баланс после транзакции')),
                ('type', models.CharField(blank=True, choices=[('BUY_TARIF', 'Покупка тарифа'), ('BUY_EMPLOYEE', 'Покупка сотрудника'), ('CONT_TARIF', 'Продление тарифа'), ('CONT_EMPLOYEE', 'Продление сотрудника'), ('OTHER', 'Прочее')], max_length=20, null=True, verbose_name='Вид Платежа')),
                ('status', models.CharField(choices=[('SUCCESS', 'Успешно'), ('FAILURE', 'Ошибка'), ('IN_PROCCESSING', 'В обработке')], default='IN_PROCCESSING', max_length=20, verbose_name='Статус')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Транзакция баланса магазина',
                'verbose_name_plural': 'Транзакции баланса магазинов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('bank_account_number', models.CharField(max_length=255, verbose_name='Номер счета')),
                ('bank_account_holder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя владельца счета')),
                ('bank_account_holder_inn', models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН владельца счета')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_details', to='stores.banketype', verbose_name='Тип банка')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Банковские реквизиты',
                'verbose_name_plural': 'Банковские реквизиты',
            },
        ),
        migrations.CreateModel(
            name='StorePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='stores/photos/', verbose_name='Фотография')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Фото магазина',
                'verbose_name_plural': 'Фото магазинов',
            },
        ),
        migrations.CreateModel(
            name='StoreTariffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('tariff_plan', models.CharField(choices=[('0', 'Бесплатный'), ('1', 'Базовый'), ('2', 'Стандарт'), ('3', 'Премиум')], max_length=1, verbose_name='Тарифный план')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала действия тарифа')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания действия тарифа')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Введите стоимость в рублях', max_digits=12, verbose_name='Стоимость тарифа')),
                ('duration_type', models.CharField(choices=[('1', '1 месяц'), ('2', '3 месяца'), ('3', '6 месяцев'), ('4', '12 месяцев')], max_length=1, verbose_name='Тип длительности тарифа')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_plans', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Тарифный план магазина',
                'verbose_name_plural': 'Тарифные планы магазинов',
                'ordering': ['-created_at'],
            },
        ),
    ]
