# Generated by Django 6.0 on 2026-03-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_fix_status_choices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankeType',
            new_name='BankType',
        ),
        migrations.AlterField(
            model_name='store',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='store',
            name='cashback_percent',
            field=models.PositiveSmallIntegerField(choices=[(1, '1%'), (2, '2%'), (3, '3%'), (4, '4%'), (5, '5%'), (6, '6%'), (7, '7%'), (8, '8%'), (9, '9%'), (10, '10%')], default=1, verbose_name='Процент кэшбэка'),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг магазина'),
        ),
        migrations.AlterField(
            model_name='storebalancetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма транзакции'),
        ),
        migrations.AlterField(
            model_name='storebalancetransaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Баланс после транзакции'),
        ),
        migrations.AlterField(
            model_name='storebalancetransaction',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Баланс до транзакции'),
        ),
        migrations.AlterField(
            model_name='storebalancetransaction',
            name='type',
            field=models.CharField(blank=True, choices=[('BUY_TARIF', 'Покупка тарифа'), ('BUY_EMPLOYEE', 'Покупка сотрудника'), ('CONT_TARIF', 'Продление тарифа'), ('CONT_EMPLOYEE', 'Продление сотрудника'), ('OTHER', 'Прочее')], max_length=20, null=True, verbose_name='Вид платежа'),
        ),
        migrations.AlterField(
            model_name='storebankdetail',
            name='bank_account_holder_inn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН владельца счёта'),
        ),
        migrations.AlterField(
            model_name='storebankdetail',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя владельца счёта'),
        ),
        migrations.AlterField(
            model_name='storebankdetail',
            name='bank_account_number',
            field=models.CharField(max_length=255, verbose_name='Номер счёта'),
        ),
        migrations.AlterField(
            model_name='storetariffplan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость тарифа'),
        ),
        migrations.AlterModelTable(
            name='banktype',
            table='stores_banketype',
        ),
    ]
