# Generated by Django 6.0 on 2026-03-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_rename_slide_ordering_to_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
    ]
