# Generated by Django 6.0 on 2026-03-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_store_balance_non_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebalancetransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Ключ идемпотентности'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='promocode_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='storebalancetransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='storebalancetransaction_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='storetariffplan',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='storetariffplan_amount_non_negative'),
        ),
    ]
