# Generated by Django 6.0 on 2026-03-13 15:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Логин сотрудника')),
                ('password', models.CharField(blank=True, help_text='Введите пароль', max_length=255, null=True, verbose_name='Пароль сотрудника')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя сотрудника')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия сотрудника')),
                ('position', models.CharField(choices=[('WAITER', 'Официант'), ('ACCOUNTAT', 'Бухгалтер'), ('CASHIER', 'Кассир')], max_length=20, verbose_name='Должность сотрудника')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Токен сессии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность сотрудника')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['first_name'],
            },
        ),
    ]
