# Generated by Django 6.0 on 2026-03-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_fix_position_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, help_text='Хранится в виде хеша Django', max_length=255, null=True, verbose_name='Пароль сотрудника'),
        ),
    ]
